#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlGenCore
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSCOMWeb")]
	public partial class MSCOMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFrameworksAndRuntime(FrameworksAndRuntime instance);
    partial void UpdateFrameworksAndRuntime(FrameworksAndRuntime instance);
    partial void DeleteFrameworksAndRuntime(FrameworksAndRuntime instance);
    partial void InsertDatabaseServer(DatabaseServer instance);
    partial void UpdateDatabaseServer(DatabaseServer instance);
    partial void DeleteDatabaseServer(DatabaseServer instance);
    partial void InsertPackage(Package instance);
    partial void UpdatePackage(Package instance);
    partial void DeletePackage(Package instance);
    partial void InsertProductOrAppCategory(ProductOrAppCategory instance);
    partial void UpdateProductOrAppCategory(ProductOrAppCategory instance);
    partial void DeleteProductOrAppCategory(ProductOrAppCategory instance);
    partial void InsertWebServerExtension(WebServerExtension instance);
    partial void UpdateWebServerExtension(WebServerExtension instance);
    partial void DeleteWebServerExtension(WebServerExtension instance);
    partial void InsertSubmission(Submission instance);
    partial void UpdateSubmission(Submission instance);
    partial void DeleteSubmission(Submission instance);
    partial void InsertSubmissionsStatus(SubmissionsStatus instance);
    partial void UpdateSubmissionsStatus(SubmissionsStatus instance);
    partial void DeleteSubmissionsStatus(SubmissionsStatus instance);
    partial void InsertSubmissionState(SubmissionState instance);
    partial void UpdateSubmissionState(SubmissionState instance);
    partial void DeleteSubmissionState(SubmissionState instance);
    #endregion
		
		public MSCOMDataContext() : 
				base(global::XmlGenCore.Properties.Settings.Default.MSCOMWebConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MSCOMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSCOMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSCOMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSCOMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FrameworksAndRuntime> FrameworksAndRuntimes
		{
			get
			{
				return this.GetTable<FrameworksAndRuntime>();
			}
		}
		
		public System.Data.Linq.Table<DatabaseServer> DatabaseServers
		{
			get
			{
				return this.GetTable<DatabaseServer>();
			}
		}
		
		public System.Data.Linq.Table<Package> Packages
		{
			get
			{
				return this.GetTable<Package>();
			}
		}
		
		public System.Data.Linq.Table<ProductOrAppCategory> ProductOrAppCategories
		{
			get
			{
				return this.GetTable<ProductOrAppCategory>();
			}
		}
		
		public System.Data.Linq.Table<WebServerExtension> WebServerExtensions
		{
			get
			{
				return this.GetTable<WebServerExtension>();
			}
		}
		
		public System.Data.Linq.Table<SubmissionLocalizedMetaData> SubmissionLocalizedMetaDatas
		{
			get
			{
				return this.GetTable<SubmissionLocalizedMetaData>();
			}
		}
		
		public System.Data.Linq.Table<Submission> Submissions
		{
			get
			{
				return this.GetTable<Submission>();
			}
		}
		
		public System.Data.Linq.Table<SubmissionsStatus> SubmissionsStatus
		{
			get
			{
				return this.GetTable<SubmissionsStatus>();
			}
		}
		
		public System.Data.Linq.Table<SubmissionState> SubmissionStates
		{
			get
			{
				return this.GetTable<SubmissionState>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllSubmissionsInBrief")]
		public ISingleResult<GetAllSubmissionsInBriefResult> GetAllSubmissionsInBrief()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllSubmissionsInBriefResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSubmittedDataForProductOrApp")]
		public ISingleResult<GetSubmittedDataForProductOrAppResult> GetSubmittedDataForProductOrApp([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubmissionID", DbType="Int")] System.Nullable<int> submissionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), submissionID);
			return ((ISingleResult<GetSubmittedDataForProductOrAppResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FrameworksAndRuntimes")]
	public partial class FrameworksAndRuntime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FrameworkOrRuntimeID;
		
		private string _Name;
		
		private string _FeedIDRef;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFrameworkOrRuntimeIDChanging(int value);
    partial void OnFrameworkOrRuntimeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFeedIDRefChanging(string value);
    partial void OnFeedIDRefChanged();
    #endregion
		
		public FrameworksAndRuntime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FrameworkOrRuntimeID
		{
			get
			{
				return this._FrameworkOrRuntimeID;
			}
			set
			{
				if ((this._FrameworkOrRuntimeID != value))
				{
					this.OnFrameworkOrRuntimeIDChanging(value);
					this.SendPropertyChanging();
					this._FrameworkOrRuntimeID = value;
					this.SendPropertyChanged("FrameworkOrRuntimeID");
					this.OnFrameworkOrRuntimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedIDRef", DbType="VarChar(50)")]
		public string FeedIDRef
		{
			get
			{
				return this._FeedIDRef;
			}
			set
			{
				if ((this._FeedIDRef != value))
				{
					this.OnFeedIDRefChanging(value);
					this.SendPropertyChanging();
					this._FeedIDRef = value;
					this.SendPropertyChanged("FeedIDRef");
					this.OnFeedIDRefChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatabaseServers")]
	public partial class DatabaseServer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DatabaseServerID;
		
		private string _Name;
		
		private string _FeedIDRef;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDatabaseServerIDChanging(int value);
    partial void OnDatabaseServerIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFeedIDRefChanging(string value);
    partial void OnFeedIDRefChanged();
    #endregion
		
		public DatabaseServer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseServerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DatabaseServerID
		{
			get
			{
				return this._DatabaseServerID;
			}
			set
			{
				if ((this._DatabaseServerID != value))
				{
					this.OnDatabaseServerIDChanging(value);
					this.SendPropertyChanging();
					this._DatabaseServerID = value;
					this.SendPropertyChanged("DatabaseServerID");
					this.OnDatabaseServerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedIDRef", DbType="VarChar(50)")]
		public string FeedIDRef
		{
			get
			{
				return this._FeedIDRef;
			}
			set
			{
				if ((this._FeedIDRef != value))
				{
					this.OnFeedIDRefChanging(value);
					this.SendPropertyChanging();
					this._FeedIDRef = value;
					this.SendPropertyChanged("FeedIDRef");
					this.OnFeedIDRefChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Packages")]
	public partial class Package : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PackageID;
		
		private int _ArchitectureTypeID;
		
		private string _PackageURL;
		
		private string _StartPage;
		
		private string _MD5Hash;
		
		private string _SHA1Hash;
		
		private System.Nullable<int> _FileSize;
		
		private string _Language;
		
		private System.Nullable<int> _SubmissionID;
		
		private EntityRef<Submission> _Submission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPackageIDChanging(int value);
    partial void OnPackageIDChanged();
    partial void OnArchitectureTypeIDChanging(int value);
    partial void OnArchitectureTypeIDChanged();
    partial void OnPackageURLChanging(string value);
    partial void OnPackageURLChanged();
    partial void OnStartPageChanging(string value);
    partial void OnStartPageChanged();
    partial void OnMD5HashChanging(string value);
    partial void OnMD5HashChanged();
    partial void OnSHA1HashChanging(string value);
    partial void OnSHA1HashChanged();
    partial void OnFileSizeChanging(System.Nullable<int> value);
    partial void OnFileSizeChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnSubmissionIDChanging(System.Nullable<int> value);
    partial void OnSubmissionIDChanged();
    #endregion
		
		public Package()
		{
			this._Submission = default(EntityRef<Submission>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this.OnPackageIDChanging(value);
					this.SendPropertyChanging();
					this._PackageID = value;
					this.SendPropertyChanged("PackageID");
					this.OnPackageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchitectureTypeID", DbType="Int NOT NULL")]
		public int ArchitectureTypeID
		{
			get
			{
				return this._ArchitectureTypeID;
			}
			set
			{
				if ((this._ArchitectureTypeID != value))
				{
					this.OnArchitectureTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ArchitectureTypeID = value;
					this.SendPropertyChanged("ArchitectureTypeID");
					this.OnArchitectureTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageURL", DbType="VarChar(512)")]
		public string PackageURL
		{
			get
			{
				return this._PackageURL;
			}
			set
			{
				if ((this._PackageURL != value))
				{
					this.OnPackageURLChanging(value);
					this.SendPropertyChanging();
					this._PackageURL = value;
					this.SendPropertyChanged("PackageURL");
					this.OnPackageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartPage", DbType="VarChar(512)")]
		public string StartPage
		{
			get
			{
				return this._StartPage;
			}
			set
			{
				if ((this._StartPage != value))
				{
					this.OnStartPageChanging(value);
					this.SendPropertyChanging();
					this._StartPage = value;
					this.SendPropertyChanged("StartPage");
					this.OnStartPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD5Hash", DbType="VarChar(250)")]
		public string MD5Hash
		{
			get
			{
				return this._MD5Hash;
			}
			set
			{
				if ((this._MD5Hash != value))
				{
					this.OnMD5HashChanging(value);
					this.SendPropertyChanging();
					this._MD5Hash = value;
					this.SendPropertyChanged("MD5Hash");
					this.OnMD5HashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHA1Hash", DbType="VarChar(250)")]
		public string SHA1Hash
		{
			get
			{
				return this._SHA1Hash;
			}
			set
			{
				if ((this._SHA1Hash != value))
				{
					this.OnSHA1HashChanging(value);
					this.SendPropertyChanging();
					this._SHA1Hash = value;
					this.SendPropertyChanged("SHA1Hash");
					this.OnSHA1HashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="Int")]
		public System.Nullable<int> FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(50)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="Int")]
		public System.Nullable<int> SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					if (this._Submission.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubmissionIDChanging(value);
					this.SendPropertyChanging();
					this._SubmissionID = value;
					this.SendPropertyChanged("SubmissionID");
					this.OnSubmissionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Submission_Package", Storage="_Submission", ThisKey="SubmissionID", OtherKey="SubmissionID", IsForeignKey=true)]
		public Submission Submission
		{
			get
			{
				return this._Submission.Entity;
			}
			set
			{
				Submission previousValue = this._Submission.Entity;
				if (((previousValue != value) 
							|| (this._Submission.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Submission.Entity = null;
						previousValue.Packages.Remove(this);
					}
					this._Submission.Entity = value;
					if ((value != null))
					{
						value.Packages.Add(this);
						this._SubmissionID = value.SubmissionID;
					}
					else
					{
						this._SubmissionID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Submission");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductOrAppCategories")]
	public partial class ProductOrAppCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public ProductOrAppCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebServerExtensions")]
	public partial class WebServerExtension : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WebServerExtensionID;
		
		private string _Name;
		
		private string _FeedIDRef;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWebServerExtensionIDChanging(int value);
    partial void OnWebServerExtensionIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFeedIDRefChanging(string value);
    partial void OnFeedIDRefChanged();
    #endregion
		
		public WebServerExtension()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebServerExtensionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WebServerExtensionID
		{
			get
			{
				return this._WebServerExtensionID;
			}
			set
			{
				if ((this._WebServerExtensionID != value))
				{
					this.OnWebServerExtensionIDChanging(value);
					this.SendPropertyChanging();
					this._WebServerExtensionID = value;
					this.SendPropertyChanged("WebServerExtensionID");
					this.OnWebServerExtensionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedIDRef", DbType="VarChar(50)")]
		public string FeedIDRef
		{
			get
			{
				return this._FeedIDRef;
			}
			set
			{
				if ((this._FeedIDRef != value))
				{
					this.OnFeedIDRefChanging(value);
					this.SendPropertyChanging();
					this._FeedIDRef = value;
					this.SendPropertyChanged("FeedIDRef");
					this.OnFeedIDRefChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubmissionLocalizedMetaData")]
	public partial class SubmissionLocalizedMetaData
	{
		
		private int _SubmissionID;
		
		private string _Language;
		
		private string _Name;
		
		private string _Description;
		
		private string _BriefDescription;
		
		public SubmissionLocalizedMetaData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="Int NOT NULL")]
		public int SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					this._SubmissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this._Language = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1500) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BriefDescription", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string BriefDescription
		{
			get
			{
				return this._BriefDescription;
			}
			set
			{
				if ((this._BriefDescription != value))
				{
					this._BriefDescription = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Submissions")]
	public partial class Submission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubmissionID;
		
		private string _Nickname;
		
		private string _Version;
		
		private string _SubmittingEntity;
		
		private string _SubmittingEntityURL;
		
		private string _AppURL;
		
		private string _SupportURL;
		
		private System.DateTime _ReleaseDate;
		
		private System.Nullable<int> _FrameworkOrRuntimeID;
		
		private string _DatabaseServerIDs;
		
		private string _WebServerExtensionIDs;
		
		private string _CategoryID1;
		
		private string _CategoryID2;
		
		private int _LogoID;
		
		private System.Nullable<int> _ScreenshotID1;
		
		private System.Nullable<int> _ScreenshotID2;
		
		private System.Nullable<int> _ScreenshotID3;
		
		private System.Nullable<int> _ScreenshotID4;
		
		private System.Nullable<int> _ScreenshotID5;
		
		private System.Nullable<int> _ScreenshotID6;
		
		private string _ProfessionalServicesURL;
		
		private string _CommercialProductURL;
		
		private bool _AgreedToTerms;
		
		private string _AdditionalInfo;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private EntitySet<Package> _Packages;
		
		private EntitySet<SubmissionsStatus> _SubmissionsStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubmissionIDChanging(int value);
    partial void OnSubmissionIDChanged();
    partial void OnNicknameChanging(string value);
    partial void OnNicknameChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnSubmittingEntityChanging(string value);
    partial void OnSubmittingEntityChanged();
    partial void OnSubmittingEntityURLChanging(string value);
    partial void OnSubmittingEntityURLChanged();
    partial void OnAppURLChanging(string value);
    partial void OnAppURLChanged();
    partial void OnSupportURLChanging(string value);
    partial void OnSupportURLChanged();
    partial void OnReleaseDateChanging(System.DateTime value);
    partial void OnReleaseDateChanged();
    partial void OnFrameworkOrRuntimeIDChanging(System.Nullable<int> value);
    partial void OnFrameworkOrRuntimeIDChanged();
    partial void OnDatabaseServerIDsChanging(string value);
    partial void OnDatabaseServerIDsChanged();
    partial void OnWebServerExtensionIDsChanging(string value);
    partial void OnWebServerExtensionIDsChanged();
    partial void OnCategoryID1Changing(string value);
    partial void OnCategoryID1Changed();
    partial void OnCategoryID2Changing(string value);
    partial void OnCategoryID2Changed();
    partial void OnLogoIDChanging(int value);
    partial void OnLogoIDChanged();
    partial void OnScreenshotID1Changing(System.Nullable<int> value);
    partial void OnScreenshotID1Changed();
    partial void OnScreenshotID2Changing(System.Nullable<int> value);
    partial void OnScreenshotID2Changed();
    partial void OnScreenshotID3Changing(System.Nullable<int> value);
    partial void OnScreenshotID3Changed();
    partial void OnScreenshotID4Changing(System.Nullable<int> value);
    partial void OnScreenshotID4Changed();
    partial void OnScreenshotID5Changing(System.Nullable<int> value);
    partial void OnScreenshotID5Changed();
    partial void OnScreenshotID6Changing(System.Nullable<int> value);
    partial void OnScreenshotID6Changed();
    partial void OnProfessionalServicesURLChanging(string value);
    partial void OnProfessionalServicesURLChanged();
    partial void OnCommercialProductURLChanging(string value);
    partial void OnCommercialProductURLChanged();
    partial void OnAgreedToTermsChanging(bool value);
    partial void OnAgreedToTermsChanged();
    partial void OnAdditionalInfoChanging(string value);
    partial void OnAdditionalInfoChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    #endregion
		
		public Submission()
		{
			this._Packages = new EntitySet<Package>(new Action<Package>(this.attach_Packages), new Action<Package>(this.detach_Packages));
			this._SubmissionsStatus = new EntitySet<SubmissionsStatus>(new Action<SubmissionsStatus>(this.attach_SubmissionsStatus), new Action<SubmissionsStatus>(this.detach_SubmissionsStatus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					this.OnSubmissionIDChanging(value);
					this.SendPropertyChanging();
					this._SubmissionID = value;
					this.SendPropertyChanged("SubmissionID");
					this.OnSubmissionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="NVarChar(255)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this.OnNicknameChanging(value);
					this.SendPropertyChanging();
					this._Nickname = value;
					this.SendPropertyChanged("Nickname");
					this.OnNicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntity", DbType="NVarChar(255)")]
		public string SubmittingEntity
		{
			get
			{
				return this._SubmittingEntity;
			}
			set
			{
				if ((this._SubmittingEntity != value))
				{
					this.OnSubmittingEntityChanging(value);
					this.SendPropertyChanging();
					this._SubmittingEntity = value;
					this.SendPropertyChanged("SubmittingEntity");
					this.OnSubmittingEntityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntityURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SubmittingEntityURL
		{
			get
			{
				return this._SubmittingEntityURL;
			}
			set
			{
				if ((this._SubmittingEntityURL != value))
				{
					this.OnSubmittingEntityURLChanging(value);
					this.SendPropertyChanging();
					this._SubmittingEntityURL = value;
					this.SendPropertyChanged("SubmittingEntityURL");
					this.OnSubmittingEntityURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string AppURL
		{
			get
			{
				return this._AppURL;
			}
			set
			{
				if ((this._AppURL != value))
				{
					this.OnAppURLChanging(value);
					this.SendPropertyChanging();
					this._AppURL = value;
					this.SendPropertyChanged("AppURL");
					this.OnAppURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SupportURL
		{
			get
			{
				return this._SupportURL;
			}
			set
			{
				if ((this._SupportURL != value))
				{
					this.OnSupportURLChanging(value);
					this.SendPropertyChanging();
					this._SupportURL = value;
					this.SendPropertyChanged("SupportURL");
					this.OnSupportURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this.OnReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._ReleaseDate = value;
					this.SendPropertyChanged("ReleaseDate");
					this.OnReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeID", DbType="Int")]
		public System.Nullable<int> FrameworkOrRuntimeID
		{
			get
			{
				return this._FrameworkOrRuntimeID;
			}
			set
			{
				if ((this._FrameworkOrRuntimeID != value))
				{
					this.OnFrameworkOrRuntimeIDChanging(value);
					this.SendPropertyChanging();
					this._FrameworkOrRuntimeID = value;
					this.SendPropertyChanged("FrameworkOrRuntimeID");
					this.OnFrameworkOrRuntimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseServerIDs", DbType="VarChar(512)")]
		public string DatabaseServerIDs
		{
			get
			{
				return this._DatabaseServerIDs;
			}
			set
			{
				if ((this._DatabaseServerIDs != value))
				{
					this.OnDatabaseServerIDsChanging(value);
					this.SendPropertyChanging();
					this._DatabaseServerIDs = value;
					this.SendPropertyChanged("DatabaseServerIDs");
					this.OnDatabaseServerIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebServerExtensionIDs", DbType="VarChar(512)")]
		public string WebServerExtensionIDs
		{
			get
			{
				return this._WebServerExtensionIDs;
			}
			set
			{
				if ((this._WebServerExtensionIDs != value))
				{
					this.OnWebServerExtensionIDsChanging(value);
					this.SendPropertyChanging();
					this._WebServerExtensionIDs = value;
					this.SendPropertyChanged("WebServerExtensionIDs");
					this.OnWebServerExtensionIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CategoryID1
		{
			get
			{
				return this._CategoryID1;
			}
			set
			{
				if ((this._CategoryID1 != value))
				{
					this.OnCategoryID1Changing(value);
					this.SendPropertyChanging();
					this._CategoryID1 = value;
					this.SendPropertyChanged("CategoryID1");
					this.OnCategoryID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID2", DbType="VarChar(255)")]
		public string CategoryID2
		{
			get
			{
				return this._CategoryID2;
			}
			set
			{
				if ((this._CategoryID2 != value))
				{
					this.OnCategoryID2Changing(value);
					this.SendPropertyChanging();
					this._CategoryID2 = value;
					this.SendPropertyChanged("CategoryID2");
					this.OnCategoryID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoID", DbType="Int NOT NULL")]
		public int LogoID
		{
			get
			{
				return this._LogoID;
			}
			set
			{
				if ((this._LogoID != value))
				{
					this.OnLogoIDChanging(value);
					this.SendPropertyChanging();
					this._LogoID = value;
					this.SendPropertyChanged("LogoID");
					this.OnLogoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID1", DbType="Int")]
		public System.Nullable<int> ScreenshotID1
		{
			get
			{
				return this._ScreenshotID1;
			}
			set
			{
				if ((this._ScreenshotID1 != value))
				{
					this.OnScreenshotID1Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID1 = value;
					this.SendPropertyChanged("ScreenshotID1");
					this.OnScreenshotID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID2", DbType="Int")]
		public System.Nullable<int> ScreenshotID2
		{
			get
			{
				return this._ScreenshotID2;
			}
			set
			{
				if ((this._ScreenshotID2 != value))
				{
					this.OnScreenshotID2Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID2 = value;
					this.SendPropertyChanged("ScreenshotID2");
					this.OnScreenshotID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID3", DbType="Int")]
		public System.Nullable<int> ScreenshotID3
		{
			get
			{
				return this._ScreenshotID3;
			}
			set
			{
				if ((this._ScreenshotID3 != value))
				{
					this.OnScreenshotID3Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID3 = value;
					this.SendPropertyChanged("ScreenshotID3");
					this.OnScreenshotID3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID4", DbType="Int")]
		public System.Nullable<int> ScreenshotID4
		{
			get
			{
				return this._ScreenshotID4;
			}
			set
			{
				if ((this._ScreenshotID4 != value))
				{
					this.OnScreenshotID4Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID4 = value;
					this.SendPropertyChanged("ScreenshotID4");
					this.OnScreenshotID4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID5", DbType="Int")]
		public System.Nullable<int> ScreenshotID5
		{
			get
			{
				return this._ScreenshotID5;
			}
			set
			{
				if ((this._ScreenshotID5 != value))
				{
					this.OnScreenshotID5Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID5 = value;
					this.SendPropertyChanged("ScreenshotID5");
					this.OnScreenshotID5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID6", DbType="Int")]
		public System.Nullable<int> ScreenshotID6
		{
			get
			{
				return this._ScreenshotID6;
			}
			set
			{
				if ((this._ScreenshotID6 != value))
				{
					this.OnScreenshotID6Changing(value);
					this.SendPropertyChanging();
					this._ScreenshotID6 = value;
					this.SendPropertyChanged("ScreenshotID6");
					this.OnScreenshotID6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessionalServicesURL", DbType="VarChar(512)")]
		public string ProfessionalServicesURL
		{
			get
			{
				return this._ProfessionalServicesURL;
			}
			set
			{
				if ((this._ProfessionalServicesURL != value))
				{
					this.OnProfessionalServicesURLChanging(value);
					this.SendPropertyChanging();
					this._ProfessionalServicesURL = value;
					this.SendPropertyChanged("ProfessionalServicesURL");
					this.OnProfessionalServicesURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommercialProductURL", DbType="VarChar(512)")]
		public string CommercialProductURL
		{
			get
			{
				return this._CommercialProductURL;
			}
			set
			{
				if ((this._CommercialProductURL != value))
				{
					this.OnCommercialProductURLChanging(value);
					this.SendPropertyChanging();
					this._CommercialProductURL = value;
					this.SendPropertyChanged("CommercialProductURL");
					this.OnCommercialProductURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgreedToTerms", DbType="Bit NOT NULL")]
		public bool AgreedToTerms
		{
			get
			{
				return this._AgreedToTerms;
			}
			set
			{
				if ((this._AgreedToTerms != value))
				{
					this.OnAgreedToTermsChanging(value);
					this.SendPropertyChanging();
					this._AgreedToTerms = value;
					this.SendPropertyChanged("AgreedToTerms");
					this.OnAgreedToTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfo", DbType="NVarChar(2048)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this.OnAdditionalInfoChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInfo = value;
					this.SendPropertyChanged("AdditionalInfo");
					this.OnAdditionalInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Submission_Package", Storage="_Packages", ThisKey="SubmissionID", OtherKey="SubmissionID")]
		public EntitySet<Package> Packages
		{
			get
			{
				return this._Packages;
			}
			set
			{
				this._Packages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Submission_SubmissionsStatus", Storage="_SubmissionsStatus", ThisKey="SubmissionID", OtherKey="SubmissionID")]
		public EntitySet<SubmissionsStatus> SubmissionsStatus
		{
			get
			{
				return this._SubmissionsStatus;
			}
			set
			{
				this._SubmissionsStatus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Packages(Package entity)
		{
			this.SendPropertyChanging();
			entity.Submission = this;
		}
		
		private void detach_Packages(Package entity)
		{
			this.SendPropertyChanging();
			entity.Submission = null;
		}
		
		private void attach_SubmissionsStatus(SubmissionsStatus entity)
		{
			this.SendPropertyChanging();
			entity.Submission = this;
		}
		
		private void detach_SubmissionsStatus(SubmissionsStatus entity)
		{
			this.SendPropertyChanging();
			entity.Submission = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubmissionsStatus")]
	public partial class SubmissionsStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubmissionID;
		
		private int _SubmissionStateID;
		
		private EntitySet<SubmissionState> _SubmissionStates;
		
		private EntityRef<Submission> _Submission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubmissionIDChanging(int value);
    partial void OnSubmissionIDChanged();
    partial void OnSubmissionStateIDChanging(int value);
    partial void OnSubmissionStateIDChanged();
    #endregion
		
		public SubmissionsStatus()
		{
			this._SubmissionStates = new EntitySet<SubmissionState>(new Action<SubmissionState>(this.attach_SubmissionStates), new Action<SubmissionState>(this.detach_SubmissionStates));
			this._Submission = default(EntityRef<Submission>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					if (this._Submission.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubmissionIDChanging(value);
					this.SendPropertyChanging();
					this._SubmissionID = value;
					this.SendPropertyChanged("SubmissionID");
					this.OnSubmissionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionStateID", DbType="Int NOT NULL")]
		public int SubmissionStateID
		{
			get
			{
				return this._SubmissionStateID;
			}
			set
			{
				if ((this._SubmissionStateID != value))
				{
					this.OnSubmissionStateIDChanging(value);
					this.SendPropertyChanging();
					this._SubmissionStateID = value;
					this.SendPropertyChanged("SubmissionStateID");
					this.OnSubmissionStateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubmissionsStatus_SubmissionState", Storage="_SubmissionStates", ThisKey="SubmissionStateID", OtherKey="SubmissionStateID")]
		public EntitySet<SubmissionState> SubmissionStates
		{
			get
			{
				return this._SubmissionStates;
			}
			set
			{
				this._SubmissionStates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Submission_SubmissionsStatus", Storage="_Submission", ThisKey="SubmissionID", OtherKey="SubmissionID", IsForeignKey=true)]
		public Submission Submission
		{
			get
			{
				return this._Submission.Entity;
			}
			set
			{
				Submission previousValue = this._Submission.Entity;
				if (((previousValue != value) 
							|| (this._Submission.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Submission.Entity = null;
						previousValue.SubmissionsStatus.Remove(this);
					}
					this._Submission.Entity = value;
					if ((value != null))
					{
						value.SubmissionsStatus.Add(this);
						this._SubmissionID = value.SubmissionID;
					}
					else
					{
						this._SubmissionID = default(int);
					}
					this.SendPropertyChanged("Submission");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubmissionStates(SubmissionState entity)
		{
			this.SendPropertyChanging();
			entity.SubmissionsStatus = this;
		}
		
		private void detach_SubmissionStates(SubmissionState entity)
		{
			this.SendPropertyChanging();
			entity.SubmissionsStatus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubmissionStates")]
	public partial class SubmissionState : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubmissionStateID;
		
		private string _Name;
		
		private string _Description;
		
		private int _SortOrder;
		
		private EntityRef<SubmissionsStatus> _SubmissionsStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubmissionStateIDChanging(int value);
    partial void OnSubmissionStateIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    #endregion
		
		public SubmissionState()
		{
			this._SubmissionsStatus = default(EntityRef<SubmissionsStatus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionStateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubmissionStateID
		{
			get
			{
				return this._SubmissionStateID;
			}
			set
			{
				if ((this._SubmissionStateID != value))
				{
					if (this._SubmissionsStatus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubmissionStateIDChanging(value);
					this.SendPropertyChanging();
					this._SubmissionStateID = value;
					this.SendPropertyChanged("SubmissionStateID");
					this.OnSubmissionStateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(512)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubmissionsStatus_SubmissionState", Storage="_SubmissionsStatus", ThisKey="SubmissionStateID", OtherKey="SubmissionStateID", IsForeignKey=true)]
		public SubmissionsStatus SubmissionsStatus
		{
			get
			{
				return this._SubmissionsStatus.Entity;
			}
			set
			{
				SubmissionsStatus previousValue = this._SubmissionsStatus.Entity;
				if (((previousValue != value) 
							|| (this._SubmissionsStatus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubmissionsStatus.Entity = null;
						previousValue.SubmissionStates.Remove(this);
					}
					this._SubmissionsStatus.Entity = value;
					if ((value != null))
					{
						value.SubmissionStates.Add(this);
						this._SubmissionStateID = value.SubmissionStateID;
					}
					else
					{
						this._SubmissionStateID = default(int);
					}
					this.SendPropertyChanged("SubmissionsStatus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetAllSubmissionsInBriefResult
	{
		
		private int _SubmissionID;
		
		private string _Nickname;
		
		private string _Version;
		
		private string _SubmittingEntity;
		
		private string _SubmittingEntityURL;
		
		private string _AppURL;
		
		private string _SupportURL;
		
		private System.DateTime _ReleaseDate;
		
		private System.Nullable<int> _FrameworkOrRuntimeID;
		
		private string _FrameworkOrRuntimeName;
		
		private string _DatabaseServerIDs;
		
		private string _WebServerExtensionIDs;
		
		private string _CategoryID1;
		
		private string _CategoryName1;
		
		private string _CategoryID2;
		
		private int _LogoID;
		
		private string _ProfessionalServicesURL;
		
		private string _CommercialProductURL;
		
		private bool _AgreedToTerms;
		
		private string _AdditionalInfo;
		
		private string _SubmissionState;
		
		private int _SubmissionStateID;
		
		private int _SubmissionStateSortOrder;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<System.DateTime> _Updated;
		
		public GetAllSubmissionsInBriefResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="Int NOT NULL")]
		public int SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					this._SubmissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="NVarChar(255)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntity", DbType="NVarChar(255)")]
		public string SubmittingEntity
		{
			get
			{
				return this._SubmittingEntity;
			}
			set
			{
				if ((this._SubmittingEntity != value))
				{
					this._SubmittingEntity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntityURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SubmittingEntityURL
		{
			get
			{
				return this._SubmittingEntityURL;
			}
			set
			{
				if ((this._SubmittingEntityURL != value))
				{
					this._SubmittingEntityURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string AppURL
		{
			get
			{
				return this._AppURL;
			}
			set
			{
				if ((this._AppURL != value))
				{
					this._AppURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SupportURL
		{
			get
			{
				return this._SupportURL;
			}
			set
			{
				if ((this._SupportURL != value))
				{
					this._SupportURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this._ReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeID", DbType="Int")]
		public System.Nullable<int> FrameworkOrRuntimeID
		{
			get
			{
				return this._FrameworkOrRuntimeID;
			}
			set
			{
				if ((this._FrameworkOrRuntimeID != value))
				{
					this._FrameworkOrRuntimeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeName", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string FrameworkOrRuntimeName
		{
			get
			{
				return this._FrameworkOrRuntimeName;
			}
			set
			{
				if ((this._FrameworkOrRuntimeName != value))
				{
					this._FrameworkOrRuntimeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseServerIDs", DbType="VarChar(512)")]
		public string DatabaseServerIDs
		{
			get
			{
				return this._DatabaseServerIDs;
			}
			set
			{
				if ((this._DatabaseServerIDs != value))
				{
					this._DatabaseServerIDs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebServerExtensionIDs", DbType="VarChar(512)")]
		public string WebServerExtensionIDs
		{
			get
			{
				return this._WebServerExtensionIDs;
			}
			set
			{
				if ((this._WebServerExtensionIDs != value))
				{
					this._WebServerExtensionIDs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CategoryID1
		{
			get
			{
				return this._CategoryID1;
			}
			set
			{
				if ((this._CategoryID1 != value))
				{
					this._CategoryID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CategoryName1
		{
			get
			{
				return this._CategoryName1;
			}
			set
			{
				if ((this._CategoryName1 != value))
				{
					this._CategoryName1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID2", DbType="VarChar(255)")]
		public string CategoryID2
		{
			get
			{
				return this._CategoryID2;
			}
			set
			{
				if ((this._CategoryID2 != value))
				{
					this._CategoryID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoID", DbType="Int NOT NULL")]
		public int LogoID
		{
			get
			{
				return this._LogoID;
			}
			set
			{
				if ((this._LogoID != value))
				{
					this._LogoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessionalServicesURL", DbType="VarChar(512)")]
		public string ProfessionalServicesURL
		{
			get
			{
				return this._ProfessionalServicesURL;
			}
			set
			{
				if ((this._ProfessionalServicesURL != value))
				{
					this._ProfessionalServicesURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommercialProductURL", DbType="VarChar(512)")]
		public string CommercialProductURL
		{
			get
			{
				return this._CommercialProductURL;
			}
			set
			{
				if ((this._CommercialProductURL != value))
				{
					this._CommercialProductURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgreedToTerms", DbType="Bit NOT NULL")]
		public bool AgreedToTerms
		{
			get
			{
				return this._AgreedToTerms;
			}
			set
			{
				if ((this._AgreedToTerms != value))
				{
					this._AgreedToTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfo", DbType="NVarChar(2048)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this._AdditionalInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionState", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SubmissionState
		{
			get
			{
				return this._SubmissionState;
			}
			set
			{
				if ((this._SubmissionState != value))
				{
					this._SubmissionState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionStateID", DbType="Int NOT NULL")]
		public int SubmissionStateID
		{
			get
			{
				return this._SubmissionStateID;
			}
			set
			{
				if ((this._SubmissionStateID != value))
				{
					this._SubmissionStateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionStateSortOrder", DbType="Int NOT NULL")]
		public int SubmissionStateSortOrder
		{
			get
			{
				return this._SubmissionStateSortOrder;
			}
			set
			{
				if ((this._SubmissionStateSortOrder != value))
				{
					this._SubmissionStateSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this._Created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class GetSubmittedDataForProductOrAppResult
	{
		
		private int _SubmissionID;
		
		private string _Nickname;
		
		private string _Version;
		
		private string _SubmittingEntity;
		
		private string _SubmittingEntityURL;
		
		private string _AppURL;
		
		private string _SupportURL;
		
		private System.DateTime _ReleaseDate;
		
		private System.Nullable<int> _FrameworkOrRuntimeID;
		
		private string _FrameworkOrRuntimeName;
		
		private string _DatabaseServerIDs;
		
		private string _WebServerExtensionIDs;
		
		private string _CategoryID1;
		
		private string _CategoryName1;
		
		private string _CategoryID2;
		
		private string _CategoryName2;
		
		private int _LogoID;
		
		private System.Nullable<System.Guid> _LogoGUID;
		
		private System.Nullable<int> _ScreenshotID1;
		
		private System.Nullable<System.Guid> _ScreenshotGUID1;
		
		private System.Nullable<int> _ScreenshotID2;
		
		private System.Nullable<System.Guid> _ScreenshotGUID2;
		
		private System.Nullable<int> _ScreenshotID3;
		
		private System.Nullable<System.Guid> _ScreenshotGUID3;
		
		private System.Nullable<int> _ScreenshotID4;
		
		private System.Nullable<System.Guid> _ScreenshotGUID4;
		
		private System.Nullable<int> _ScreenshotID5;
		
		private System.Nullable<System.Guid> _ScreenshotGUID5;
		
		private System.Nullable<int> _ScreenshotID6;
		
		private System.Nullable<System.Guid> _ScreenshotGUID6;
		
		private string _ProfessionalServicesURL;
		
		private string _CommercialProductURL;
		
		private bool _AgreedToTerms;
		
		private string _AdditionalInfo;
		
		private string _SubmissionState;
		
		public GetSubmittedDataForProductOrAppResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionID", DbType="Int NOT NULL")]
		public int SubmissionID
		{
			get
			{
				return this._SubmissionID;
			}
			set
			{
				if ((this._SubmissionID != value))
				{
					this._SubmissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="NVarChar(255)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntity", DbType="NVarChar(255)")]
		public string SubmittingEntity
		{
			get
			{
				return this._SubmittingEntity;
			}
			set
			{
				if ((this._SubmittingEntity != value))
				{
					this._SubmittingEntity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittingEntityURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SubmittingEntityURL
		{
			get
			{
				return this._SubmittingEntityURL;
			}
			set
			{
				if ((this._SubmittingEntityURL != value))
				{
					this._SubmittingEntityURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string AppURL
		{
			get
			{
				return this._AppURL;
			}
			set
			{
				if ((this._AppURL != value))
				{
					this._AppURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportURL", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SupportURL
		{
			get
			{
				return this._SupportURL;
			}
			set
			{
				if ((this._SupportURL != value))
				{
					this._SupportURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this._ReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeID", DbType="Int")]
		public System.Nullable<int> FrameworkOrRuntimeID
		{
			get
			{
				return this._FrameworkOrRuntimeID;
			}
			set
			{
				if ((this._FrameworkOrRuntimeID != value))
				{
					this._FrameworkOrRuntimeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrameworkOrRuntimeName", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string FrameworkOrRuntimeName
		{
			get
			{
				return this._FrameworkOrRuntimeName;
			}
			set
			{
				if ((this._FrameworkOrRuntimeName != value))
				{
					this._FrameworkOrRuntimeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseServerIDs", DbType="VarChar(512)")]
		public string DatabaseServerIDs
		{
			get
			{
				return this._DatabaseServerIDs;
			}
			set
			{
				if ((this._DatabaseServerIDs != value))
				{
					this._DatabaseServerIDs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebServerExtensionIDs", DbType="VarChar(512)")]
		public string WebServerExtensionIDs
		{
			get
			{
				return this._WebServerExtensionIDs;
			}
			set
			{
				if ((this._WebServerExtensionIDs != value))
				{
					this._WebServerExtensionIDs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CategoryID1
		{
			get
			{
				return this._CategoryID1;
			}
			set
			{
				if ((this._CategoryID1 != value))
				{
					this._CategoryID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CategoryName1
		{
			get
			{
				return this._CategoryName1;
			}
			set
			{
				if ((this._CategoryName1 != value))
				{
					this._CategoryName1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID2", DbType="VarChar(255)")]
		public string CategoryID2
		{
			get
			{
				return this._CategoryID2;
			}
			set
			{
				if ((this._CategoryID2 != value))
				{
					this._CategoryID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName2", DbType="VarChar(255)")]
		public string CategoryName2
		{
			get
			{
				return this._CategoryName2;
			}
			set
			{
				if ((this._CategoryName2 != value))
				{
					this._CategoryName2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoID", DbType="Int NOT NULL")]
		public int LogoID
		{
			get
			{
				return this._LogoID;
			}
			set
			{
				if ((this._LogoID != value))
				{
					this._LogoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoGUID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> LogoGUID
		{
			get
			{
				return this._LogoGUID;
			}
			set
			{
				if ((this._LogoGUID != value))
				{
					this._LogoGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID1", DbType="Int")]
		public System.Nullable<int> ScreenshotID1
		{
			get
			{
				return this._ScreenshotID1;
			}
			set
			{
				if ((this._ScreenshotID1 != value))
				{
					this._ScreenshotID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID1", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID1
		{
			get
			{
				return this._ScreenshotGUID1;
			}
			set
			{
				if ((this._ScreenshotGUID1 != value))
				{
					this._ScreenshotGUID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID2", DbType="Int")]
		public System.Nullable<int> ScreenshotID2
		{
			get
			{
				return this._ScreenshotID2;
			}
			set
			{
				if ((this._ScreenshotID2 != value))
				{
					this._ScreenshotID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID2", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID2
		{
			get
			{
				return this._ScreenshotGUID2;
			}
			set
			{
				if ((this._ScreenshotGUID2 != value))
				{
					this._ScreenshotGUID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID3", DbType="Int")]
		public System.Nullable<int> ScreenshotID3
		{
			get
			{
				return this._ScreenshotID3;
			}
			set
			{
				if ((this._ScreenshotID3 != value))
				{
					this._ScreenshotID3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID3", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID3
		{
			get
			{
				return this._ScreenshotGUID3;
			}
			set
			{
				if ((this._ScreenshotGUID3 != value))
				{
					this._ScreenshotGUID3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID4", DbType="Int")]
		public System.Nullable<int> ScreenshotID4
		{
			get
			{
				return this._ScreenshotID4;
			}
			set
			{
				if ((this._ScreenshotID4 != value))
				{
					this._ScreenshotID4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID4", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID4
		{
			get
			{
				return this._ScreenshotGUID4;
			}
			set
			{
				if ((this._ScreenshotGUID4 != value))
				{
					this._ScreenshotGUID4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID5", DbType="Int")]
		public System.Nullable<int> ScreenshotID5
		{
			get
			{
				return this._ScreenshotID5;
			}
			set
			{
				if ((this._ScreenshotID5 != value))
				{
					this._ScreenshotID5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID5", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID5
		{
			get
			{
				return this._ScreenshotGUID5;
			}
			set
			{
				if ((this._ScreenshotGUID5 != value))
				{
					this._ScreenshotGUID5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotID6", DbType="Int")]
		public System.Nullable<int> ScreenshotID6
		{
			get
			{
				return this._ScreenshotID6;
			}
			set
			{
				if ((this._ScreenshotID6 != value))
				{
					this._ScreenshotID6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenshotGUID6", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ScreenshotGUID6
		{
			get
			{
				return this._ScreenshotGUID6;
			}
			set
			{
				if ((this._ScreenshotGUID6 != value))
				{
					this._ScreenshotGUID6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessionalServicesURL", DbType="VarChar(512)")]
		public string ProfessionalServicesURL
		{
			get
			{
				return this._ProfessionalServicesURL;
			}
			set
			{
				if ((this._ProfessionalServicesURL != value))
				{
					this._ProfessionalServicesURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommercialProductURL", DbType="VarChar(512)")]
		public string CommercialProductURL
		{
			get
			{
				return this._CommercialProductURL;
			}
			set
			{
				if ((this._CommercialProductURL != value))
				{
					this._CommercialProductURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgreedToTerms", DbType="Bit NOT NULL")]
		public bool AgreedToTerms
		{
			get
			{
				return this._AgreedToTerms;
			}
			set
			{
				if ((this._AgreedToTerms != value))
				{
					this._AgreedToTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfo", DbType="NVarChar(2048)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this._AdditionalInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionState", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SubmissionState
		{
			get
			{
				return this._SubmissionState;
			}
			set
			{
				if ((this._SubmissionState != value))
				{
					this._SubmissionState = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
