<?xml version="1.0" encoding="utf-8"?><Database Name="MSCOMWeb" Class="MSCOMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BAYMSFTSQLWWW23,2373;Initial Catalog=MSCOMWeb;User ID=MSCOMWeb_User;Connect Timeout=240" SettingsObjectName="XmlGenCore.Properties.Settings" SettingsPropertyName="MSCOMWebConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FrameworksAndRuntimes" Member="FrameworksAndRuntimes">
    <Type Name="FrameworksAndRuntime">
      <Column Name="FrameworkOrRuntimeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="FeedIDRef" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatabaseServers" Member="DatabaseServers">
    <Type Name="DatabaseServer">
      <Column Name="DatabaseServerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="FeedIDRef" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Packages" Member="Packages">
    <Type Name="Package">
      <Column Name="PackageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArchitectureTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PackageURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="StartPage" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="MD5Hash" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SHA1Hash" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Submission_Package" Member="Submission" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="Submission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductOrAppCategories" Member="ProductOrAppCategories">
    <Type Name="ProductOrAppCategory">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WebServerExtensions" Member="WebServerExtensions">
    <Type Name="WebServerExtension">
      <Column Name="WebServerExtensionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="FeedIDRef" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubmissionLocalizedMetaData" Member="SubmissionLocalizedMetaDatas">
    <Type Name="SubmissionLocalizedMetaData">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="BriefDescription" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Association Name="Submission_SubmissionLocalizedMetaData" Member="Submission" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="Submission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Submissions" Member="Submissions">
    <Type Name="Submission">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubmittingEntity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubmittingEntityURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="AppURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="SupportURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FrameworkOrRuntimeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DatabaseServerIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="WebServerExtensionIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CategoryID1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LogoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScreenshotID1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotID2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotID3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotID4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotID5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotID6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProfessionalServicesURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CommercialProductURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="AgreedToTerms" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Submission_SubmissionLocalizedMetaData" Member="SubmissionLocalizedMetaDatas" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="SubmissionLocalizedMetaData" />
      <Association Name="Submission_Package" Member="Packages" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="Package" />
      <Association Name="Submission_SubmissionsStatus" Member="SubmissionsStatus" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="SubmissionsStatus" />
    </Type>
  </Table>
  <Table Name="dbo.SubmissionsStatus" Member="SubmissionsStatus">
    <Type Name="SubmissionsStatus">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubmissionStateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SubmissionsStatus_SubmissionState" Member="SubmissionStates" ThisKey="SubmissionStateID" OtherKey="SubmissionStateID" Type="SubmissionState" />
      <Association Name="Submission_SubmissionsStatus" Member="Submission" ThisKey="SubmissionID" OtherKey="SubmissionID" Type="Submission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubmissionStates" Member="SubmissionStates">
    <Type Name="SubmissionState">
      <Column Name="SubmissionStateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SubmissionsStatus_SubmissionState" Member="SubmissionsStatus" ThisKey="SubmissionStateID" OtherKey="SubmissionStateID" Type="SubmissionsStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAllSubmissionsInBrief" Method="GetAllSubmissionsInBrief">
    <ElementType Name="GetAllSubmissionsInBriefResult">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubmittingEntity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubmittingEntityURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="AppURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="SupportURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FrameworkOrRuntimeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FrameworkOrRuntimeName" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseServerIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="WebServerExtensionIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CategoryID1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LogoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfessionalServicesURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CommercialProductURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="AgreedToTerms" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="SubmissionState" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubmissionStateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubmissionStateSortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSubmittedDataForProductOrApp" Method="GetSubmittedDataForProductOrApp">
    <Parameter Name="SubmissionID" Parameter="submissionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSubmittedDataForProductOrAppResult">
      <Column Name="SubmissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubmittingEntity" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubmittingEntityURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="AppURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="SupportURL" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FrameworkOrRuntimeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FrameworkOrRuntimeName" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseServerIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="WebServerExtensionIDs" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CategoryID1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CategoryName2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LogoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogoGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID4" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID5" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScreenshotID6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScreenshotGUID6" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ProfessionalServicesURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="CommercialProductURL" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="AgreedToTerms" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="SubmissionState" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>