//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomActivities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Feed")]
        public string FeedDirectory {
            get {
                return ((string)(this["FeedDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkID=282689")]
        public string WebProductList {
            get {
                return ((string)(this["WebProductList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IIS-SBH405-V10;Initial Catalog=TrackingWorkFlow;;uid=sa;pwd=iis6!dfu")]
        public string TrackingDb {
            get {
                return ((string)(this["TrackingDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=webpitest;AccountKey=GUpp23Y6qr1LtD/jd" +
            "XWQjxPwkbS6LfgSyKSSxS0KSZTtaAeZXU3e0pmPr918Xq+igae9QZb9ztgUPvsoQJs4DA==")]
        public string TC2BlobStorage {
            get {
                return ((string)(this["TC2BlobStorage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Feed\\Parameters.xsd")]
        public string ParametersXsd {
            get {
                return ((string)(this["ParametersXsd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpitest.blob.core.windows.net/backup-packages/")]
        public string TC2PackagePath {
            get {
                return ((string)(this["TC2PackagePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Feed")]
        public string TempDownloadDirectory {
            get {
                return ((string)(this["TempDownloadDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=auxmktplceprod;AccountKey=7FUA4jnShrZB" +
            "af2FKLXTSF1aRlfZHqo4WkuXOamQNyw8JQVSHY80s7SazKYifpgRYOl+u1/aQqqKQZ4B5jtmCQ==")]
        public string ProdBlobStorage {
            get {
                return ((string)(this["ProdBlobStorage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\iisdist\\appgallery\\AzureBackup")]
        public string ProdBackupPath {
            get {
                return ((string)(this["ProdBackupPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebApplicationListProdDemo.xml")]
        public string ProdFeedName {
            get {
                return ((string)(this["ProdFeedName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v-gaw@microsoft.com")]
        public string VendorEmail {
            get {
                return ((string)(this["VendorEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v-gaw@microsoft.com")]
        public string AdminEmail {
            get {
                return ((string)(this["AdminEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string BackupDirectoryCount {
            get {
                return ((string)(this["BackupDirectoryCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebApplicationListTC2Demo.xml")]
        public string TC2FeedName {
            get {
                return ((string)(this["TC2FeedName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A_Test_")]
        public string TestPackagePrefix {
            get {
                return ((string)(this["TestPackagePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\iisdist\\appgallery\\AzureGallery\\TC2")]
        public string TC2BackupPath {
            get {
                return ((string)(this["TC2BackupPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("appfeed")]
        public string TC2FeedContainer {
            get {
                return ((string)(this["TC2FeedContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("backup-packages")]
        public string TC2PackageContainer {
            get {
                return ((string)(this["TC2PackageContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("appfeed")]
        public string ProdFeedContainer {
            get {
                return ((string)(this["ProdFeedContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("packages")]
        public string ProdPackageContainer {
            get {
                return ((string)(this["ProdPackageContainer"]));
            }
        }
    }
}
