//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlGenCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Directory {
            get {
                return ((string)(this["Directory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WWWICP02;Initial Catalog=MSCOMWeb;User ID=MSCOMWeb_User;Password=MSCO" +
            "MWebU$er;Connect Timeout=240")]
        public string MSCOMWebConnectionString {
            get {
                return ((string)(this["MSCOMWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en,de,es,fr,it,ja,ko,ru,zh-cn,zh-tw,cs,he,pt-br,pl,tr,pt-pt,zh-hk")]
        public string languages {
            get {
                return ((string)(this["languages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-de,es-es,fr-fr,he-il,it-it,ja-jp,ko-kr,ru-ru,pt-pt,tr-tr,zh-cht,pt-br,zh-chs,z" +
            "h-hk,cs-cz,ar-ag,pl-pl,zh-hk")]
        public string resourceLanguages {
            get {
                return ((string)(this["resourceLanguages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkID=287078")]
        public string LiveAppFeed {
            get {
                return ((string)(this["LiveAppFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UmbracoCMS5,Umbraco,OrchardCMS,nopCommerce")]
        public string SQLCEApps {
            get {
                return ((string)(this["SQLCEApps"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RakuCMS,DotNetAge,Tiki,SplendidCRM,WordPressJa")]
        public string IIS7Apps {
            get {
                return ((string)(this["IIS7Apps"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkID=233772")]
        public string AzureProdFeed {
            get {
                return ((string)(this["AzureProdFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkID=242947")]
        public string AzureTC2Feed {
            get {
                return ((string)(this["AzureTC2Feed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpitest.blob.core.windows.net/backup-packages")]
        public string AzureTC2Blob {
            get {
                return ((string)(this["AzureTC2Blob"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://auxmktplceprod.blob.core.windows.net/packages")]
        public string AzurePRODBlob {
            get {
                return ((string)(this["AzurePRODBlob"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/?linkid=9821097")]
        public string KatalFeed {
            get {
                return ((string)(this["KatalFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.microsoft.com/web/webmatrix/2.0/discovery.txt")]
        public string DiscoveryFeed {
            get {
                return ((string)(this["DiscoveryFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkID=282689")]
        public string LiveProductFeed {
            get {
                return ((string)(this["LiveProductFeed"]));
            }
        }
    }
}
