//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FmsWeb.FmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Submission", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Submission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AzureInstallerUrlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackupLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscoveryFeedRequiresUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FmsWeb.FmsService.Fault[] FaultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAzureReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LiveInstallerUrlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FmsWeb.FmsService.SubmissionStatus[] StatusesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FmsWeb.FmsService.SubmissionType SubmissionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TC2InstallerUrlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AzureInstallerUrls {
            get {
                return this.AzureInstallerUrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.AzureInstallerUrlsField, value) != true)) {
                    this.AzureInstallerUrlsField = value;
                    this.RaisePropertyChanged("AzureInstallerUrls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackupLocation {
            get {
                return this.BackupLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.BackupLocationField, value) != true)) {
                    this.BackupLocationField = value;
                    this.RaisePropertyChanged("BackupLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiscoveryFeedRequiresUpdate {
            get {
                return this.DiscoveryFeedRequiresUpdateField;
            }
            set {
                if ((this.DiscoveryFeedRequiresUpdateField.Equals(value) != true)) {
                    this.DiscoveryFeedRequiresUpdateField = value;
                    this.RaisePropertyChanged("DiscoveryFeedRequiresUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Failed {
            get {
                return this.FailedField;
            }
            set {
                if ((this.FailedField.Equals(value) != true)) {
                    this.FailedField = value;
                    this.RaisePropertyChanged("Failed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FmsWeb.FmsService.Fault[] Faults {
            get {
                return this.FaultsField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultsField, value) != true)) {
                    this.FaultsField = value;
                    this.RaisePropertyChanged("Faults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feed {
            get {
                return this.FeedField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedField, value) != true)) {
                    this.FeedField = value;
                    this.RaisePropertyChanged("Feed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAzureReady {
            get {
                return this.IsAzureReadyField;
            }
            set {
                if ((this.IsAzureReadyField.Equals(value) != true)) {
                    this.IsAzureReadyField = value;
                    this.RaisePropertyChanged("IsAzureReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LiveInstallerUrls {
            get {
                return this.LiveInstallerUrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.LiveInstallerUrlsField, value) != true)) {
                    this.LiveInstallerUrlsField = value;
                    this.RaisePropertyChanged("LiveInstallerUrls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FmsWeb.FmsService.SubmissionStatus[] Statuses {
            get {
                return this.StatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusesField, value) != true)) {
                    this.StatusesField = value;
                    this.RaisePropertyChanged("Statuses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FmsWeb.FmsService.SubmissionType SubmissionType {
            get {
                return this.SubmissionTypeField;
            }
            set {
                if ((this.SubmissionTypeField.Equals(value) != true)) {
                    this.SubmissionTypeField = value;
                    this.RaisePropertyChanged("SubmissionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TC2InstallerUrls {
            get {
                return this.TC2InstallerUrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.TC2InstallerUrlsField, value) != true)) {
                    this.TC2InstallerUrlsField = value;
                    this.RaisePropertyChanged("TC2InstallerUrls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowInstanceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityName {
            get {
                return this.ActivityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityNameField, value) != true)) {
                    this.ActivityNameField = value;
                    this.RaisePropertyChanged("ActivityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultDetails {
            get {
                return this.FaultDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultDetailsField, value) != true)) {
                    this.FaultDetailsField = value;
                    this.RaisePropertyChanged("FaultDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeCreated {
            get {
                return this.TimeCreatedField;
            }
            set {
                if ((this.TimeCreatedField.Equals(value) != true)) {
                    this.TimeCreatedField = value;
                    this.RaisePropertyChanged("TimeCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowInstanceId {
            get {
                return this.WorkflowInstanceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowInstanceIdField, value) != true)) {
                    this.WorkflowInstanceIdField = value;
                    this.RaisePropertyChanged("WorkflowInstanceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmissionStatus", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class SubmissionStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Log {
            get {
                return this.LogField;
            }
            set {
                if ((object.ReferenceEquals(this.LogField, value) != true)) {
                    this.LogField = value;
                    this.RaisePropertyChanged("Log");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pass {
            get {
                return this.PassField;
            }
            set {
                if ((this.PassField.Equals(value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmissionType", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum SubmissionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Azure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Katal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebMatrix = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CloseTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscoveryFeedRequiresUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CloseTransaction {
            get {
                return this.CloseTransactionField;
            }
            set {
                if ((this.CloseTransactionField.Equals(value) != true)) {
                    this.CloseTransactionField = value;
                    this.RaisePropertyChanged("CloseTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiscoveryFeedRequiresUpdate {
            get {
                return this.DiscoveryFeedRequiresUpdateField;
            }
            set {
                if ((this.DiscoveryFeedRequiresUpdateField.Equals(value) != true)) {
                    this.DiscoveryFeedRequiresUpdateField = value;
                    this.RaisePropertyChanged("DiscoveryFeedRequiresUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feed {
            get {
                return this.FeedField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedField, value) != true)) {
                    this.FeedField = value;
                    this.RaisePropertyChanged("Feed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FmsResponse", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class FmsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FmsWeb.FmsService.Submission SubmissionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FmsWeb.FmsService.Submission Submission {
            get {
                return this.SubmissionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionField, value) != true)) {
                    this.SubmissionField = value;
                    this.RaisePropertyChanged("Submission");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitAppId", Namespace="http://localhost/")]
    [System.SerializableAttribute()]
    public partial class SubmitAppId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appId {
            get {
                return this.appIdField;
            }
            set {
                if ((object.ReferenceEquals(this.appIdField, value) != true)) {
                    this.appIdField = value;
                    this.RaisePropertyChanged("appId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appVersion {
            get {
                return this.appVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.appVersionField, value) != true)) {
                    this.appVersionField = value;
                    this.RaisePropertyChanged("appVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="FmsService.IFms")]
    public interface IFms {
        
        // CODEGEN: Generating message contract since the operation SubmitAppId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/SubmitAppId", ReplyAction="http://localhost/IFms/SubmitAppIdResponse")]
        FmsWeb.FmsService.SubmitAppIdResponse SubmitAppId(FmsWeb.FmsService.SubmitAppIdRequest request);
        
        // CODEGEN: Generating message contract since the operation GenerateAndValidate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/GenerateAndValidate", ReplyAction="http://localhost/IFms/GenerateAndValidateResponse")]
        FmsWeb.FmsService.GenerateAndValidateResponse GenerateAndValidate(FmsWeb.FmsService.GenerateAndValidateRequest request);
        
        // CODEGEN: Generating message contract since the operation ContinueToTC2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/ContinueToTC2", ReplyAction="http://localhost/IFms/ContinueToTC2Response")]
        FmsWeb.FmsService.ContinueToTC2Response ContinueToTC2(FmsWeb.FmsService.ContinueToTC2Request request);
        
        // CODEGEN: Generating message contract since the operation VendorTC2Response is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/VendorTC2Response", ReplyAction="http://localhost/IFms/VendorTC2ResponseResponse")]
        FmsWeb.FmsService.VendorTC2ResponseResponse VendorTC2Response(FmsWeb.FmsService.VendorTC2ResponseRequest request);
        
        // CODEGEN: Generating message contract since the operation ContinueToProd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/ContinueToProd", ReplyAction="http://localhost/IFms/ContinueToProdResponse")]
        FmsWeb.FmsService.ContinueToProdResponse ContinueToProd(FmsWeb.FmsService.ContinueToProdRequest request);
        
        // CODEGEN: Generating message contract since the operation BackupFeedAndPackages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/BackupFeedAndPackages", ReplyAction="http://localhost/IFms/BackupFeedAndPackagesResponse")]
        FmsWeb.FmsService.BackupFeedAndPackagesResponse BackupFeedAndPackages(FmsWeb.FmsService.BackupFeedAndPackagesRequest request);
        
        // CODEGEN: Generating message contract since the operation PublishToProd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/PublishToProd", ReplyAction="http://localhost/IFms/PublishToProdResponse")]
        FmsWeb.FmsService.PublishToProdResponse PublishToProd(FmsWeb.FmsService.PublishToProdRequest request);
        
        // CODEGEN: Generating message contract since the operation TakeActionToFix is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IFms/TakeActionToFix", ReplyAction="http://localhost/IFms/TakeActionToFixResponse")]
        FmsWeb.FmsService.TakeActionToFixResponse TakeActionToFix(FmsWeb.FmsService.TakeActionToFixRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitAppIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public FmsWeb.FmsService.SubmitAppId SubmitAppId;
        
        public SubmitAppIdRequest() {
        }
        
        public SubmitAppIdRequest(FmsWeb.FmsService.SubmitAppId SubmitAppId) {
            this.SubmitAppId = SubmitAppId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitAppIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public SubmitAppIdResponse() {
        }
        
        public SubmitAppIdResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public GenerateAndValidateRequest() {
        }
        
        public GenerateAndValidateRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAndValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public GenerateAndValidateResponse() {
        }
        
        public GenerateAndValidateResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueToTC2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public ContinueToTC2Request() {
        }
        
        public ContinueToTC2Request(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueToTC2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public ContinueToTC2Response() {
        }
        
        public ContinueToTC2Response(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VendorTC2ResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public VendorTC2ResponseRequest() {
        }
        
        public VendorTC2ResponseRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VendorTC2ResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.FmsResponse FmsResponse;
        
        public VendorTC2ResponseResponse() {
        }
        
        public VendorTC2ResponseResponse(FmsWeb.FmsService.FmsResponse FmsResponse) {
            this.FmsResponse = FmsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueToProdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public ContinueToProdRequest() {
        }
        
        public ContinueToProdRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContinueToProdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public ContinueToProdResponse() {
        }
        
        public ContinueToProdResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BackupFeedAndPackagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public BackupFeedAndPackagesRequest() {
        }
        
        public BackupFeedAndPackagesRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BackupFeedAndPackagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public BackupFeedAndPackagesResponse() {
        }
        
        public BackupFeedAndPackagesResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PublishToProdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public PublishToProdRequest() {
        }
        
        public PublishToProdRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PublishToProdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public PublishToProdResponse() {
        }
        
        public PublishToProdResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TakeActionToFixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.UserRequest UserRequest;
        
        public TakeActionToFixRequest() {
        }
        
        public TakeActionToFixRequest(FmsWeb.FmsService.UserRequest UserRequest) {
            this.UserRequest = UserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TakeActionToFixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model", Order=0)]
        public FmsWeb.FmsService.Submission Submission;
        
        public TakeActionToFixResponse() {
        }
        
        public TakeActionToFixResponse(FmsWeb.FmsService.Submission Submission) {
            this.Submission = Submission;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFmsChannel : FmsWeb.FmsService.IFms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FmsClient : System.ServiceModel.ClientBase<FmsWeb.FmsService.IFms>, FmsWeb.FmsService.IFms {
        
        public FmsClient() {
        }
        
        public FmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.SubmitAppIdResponse FmsWeb.FmsService.IFms.SubmitAppId(FmsWeb.FmsService.SubmitAppIdRequest request) {
            return base.Channel.SubmitAppId(request);
        }
        
        public FmsWeb.FmsService.Submission SubmitAppId(FmsWeb.FmsService.SubmitAppId SubmitAppId1) {
            FmsWeb.FmsService.SubmitAppIdRequest inValue = new FmsWeb.FmsService.SubmitAppIdRequest();
            inValue.SubmitAppId = SubmitAppId1;
            FmsWeb.FmsService.SubmitAppIdResponse retVal = ((FmsWeb.FmsService.IFms)(this)).SubmitAppId(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.GenerateAndValidateResponse FmsWeb.FmsService.IFms.GenerateAndValidate(FmsWeb.FmsService.GenerateAndValidateRequest request) {
            return base.Channel.GenerateAndValidate(request);
        }
        
        public FmsWeb.FmsService.Submission GenerateAndValidate(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.GenerateAndValidateRequest inValue = new FmsWeb.FmsService.GenerateAndValidateRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.GenerateAndValidateResponse retVal = ((FmsWeb.FmsService.IFms)(this)).GenerateAndValidate(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.ContinueToTC2Response FmsWeb.FmsService.IFms.ContinueToTC2(FmsWeb.FmsService.ContinueToTC2Request request) {
            return base.Channel.ContinueToTC2(request);
        }
        
        public FmsWeb.FmsService.Submission ContinueToTC2(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.ContinueToTC2Request inValue = new FmsWeb.FmsService.ContinueToTC2Request();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.ContinueToTC2Response retVal = ((FmsWeb.FmsService.IFms)(this)).ContinueToTC2(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.VendorTC2ResponseResponse FmsWeb.FmsService.IFms.VendorTC2Response(FmsWeb.FmsService.VendorTC2ResponseRequest request) {
            return base.Channel.VendorTC2Response(request);
        }
        
        public FmsWeb.FmsService.FmsResponse VendorTC2Response(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.VendorTC2ResponseRequest inValue = new FmsWeb.FmsService.VendorTC2ResponseRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.VendorTC2ResponseResponse retVal = ((FmsWeb.FmsService.IFms)(this)).VendorTC2Response(inValue);
            return retVal.FmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.ContinueToProdResponse FmsWeb.FmsService.IFms.ContinueToProd(FmsWeb.FmsService.ContinueToProdRequest request) {
            return base.Channel.ContinueToProd(request);
        }
        
        public FmsWeb.FmsService.Submission ContinueToProd(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.ContinueToProdRequest inValue = new FmsWeb.FmsService.ContinueToProdRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.ContinueToProdResponse retVal = ((FmsWeb.FmsService.IFms)(this)).ContinueToProd(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.BackupFeedAndPackagesResponse FmsWeb.FmsService.IFms.BackupFeedAndPackages(FmsWeb.FmsService.BackupFeedAndPackagesRequest request) {
            return base.Channel.BackupFeedAndPackages(request);
        }
        
        public FmsWeb.FmsService.Submission BackupFeedAndPackages(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.BackupFeedAndPackagesRequest inValue = new FmsWeb.FmsService.BackupFeedAndPackagesRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.BackupFeedAndPackagesResponse retVal = ((FmsWeb.FmsService.IFms)(this)).BackupFeedAndPackages(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.PublishToProdResponse FmsWeb.FmsService.IFms.PublishToProd(FmsWeb.FmsService.PublishToProdRequest request) {
            return base.Channel.PublishToProd(request);
        }
        
        public FmsWeb.FmsService.Submission PublishToProd(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.PublishToProdRequest inValue = new FmsWeb.FmsService.PublishToProdRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.PublishToProdResponse retVal = ((FmsWeb.FmsService.IFms)(this)).PublishToProd(inValue);
            return retVal.Submission;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FmsWeb.FmsService.TakeActionToFixResponse FmsWeb.FmsService.IFms.TakeActionToFix(FmsWeb.FmsService.TakeActionToFixRequest request) {
            return base.Channel.TakeActionToFix(request);
        }
        
        public FmsWeb.FmsService.Submission TakeActionToFix(FmsWeb.FmsService.UserRequest UserRequest) {
            FmsWeb.FmsService.TakeActionToFixRequest inValue = new FmsWeb.FmsService.TakeActionToFixRequest();
            inValue.UserRequest = UserRequest;
            FmsWeb.FmsService.TakeActionToFixResponse retVal = ((FmsWeb.FmsService.IFms)(this)).TakeActionToFix(inValue);
            return retVal.Submission;
        }
    }
}
